FROM golang:1.25.5-alpine

WORKDIR /app

# Устанавливаем Air для горячей перезагрузки
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

# Копируем остальной код (хотя в dev он будет перекрыт Volume)
COPY . .

# Запускаем air
CMD ["air", "-c", ".air.toml"]